version: '3'

services:
  app:
    container_name: app
    build: 
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/demo:/app
    ports:
      - 8080:8080
    tty: true
